database:
  hostname: localhost:3306
  database: replaysystem_db
  user: replaysystem_user
  password: 123456
  connection-parameters: "?autoReconnect=true&initialTimeout=1&useSSL=false"

replay-metadata: true # to use metadata api, you have to install this api in each record/replay server

replay-delete-event: false # require enable replay-metadata
delete-check-interval: 60 # min
replay-server: false